# Generated by Django 5.1.2 on 2024-10-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('ticketsdtails', models.TextField()),
                ('comment', models.CharField(max_length=75)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('piority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('Duedate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
